export const SUBMIT_SOURCE = "SUBMIT_SOURCE";
export const SUBMIT_SOURCE_SUCCESS = "SUBMIT_SOURCE_SUCCESS";
export const SOURCES_API_ERROR = "SOURCES_API_ERROR";
export const LOAD_SOURCES = "LOAD_SOURCES";
export const LOAD_SOURCES_SUCCESS = "LOAD_SOURCES_SUCCESS";
export const LOAD_SOURCES_BY_TYPE = "LOAD_SOURCES_BY_TYPE";
export const LOAD_SOURCES_BY_TYPE_SUCCESS = "LOAD_SOURCES_BY_TYPE_SUCCESS";
