export const SUBMIT_EXPENSE = "SUBMIT_EXPENSE";
export const SUBMIT_EXPENSE_SUCCESS = "SUBMIT_EXPENSE_SUCCESS";
export const EXPENSES_API_ERROR = "EXPENSES_API_ERROR";
export const LOAD_EXPENSES = "LOAD_EXPENSES";
export const LOAD_EXPENSES_SUCCESS = "LOAD_EXPENSES_SUCCESS";
