export const SUBMIT_BUYERS = "SUBMIT_BUYERS";
export const SUBMIT_BUYERS_SUCCESS = "SUBMIT_BUYERS_SUCCESS";
export const UPDATE_BUYERS = "UPDATE_BUYERS";
export const UPDATE_BUYERS_SUCCESS = "UPDATE_BUYERS_SUCCESS";
export const LOAD_BUYERS = "LOAD_BUYERS";
export const LOAD_BUYERS_SUCCESS = "LOAD_BUYERS_SUCCESS";
export const BUYER_API_ERROR = "BUYER_API_ERROR";
