export const SUBMIT_GIFTCARDS = "SUBMIT_GIFTCARDS";
export const SUBMIT_GIFTCARDS_SUCCESS = "SUBMIT_GIFTCARDS_SUCCESS";
export const LOAD_GIFTCARDS = "LOAD_GIFTCARDS";
export const LOAD_GIFTCARDS_SUCCESS = "LOAD_GIFTCARDS_SUCCESS";
export const GIFTCARDS_API_ERROR = "GIFTCARDS_API_ERROR";
