export const SUBMIT_EMPLOYEE = "SUBMIT_EMPLOYEE";
export const SUBMIT_EMPLOYEE_SUCCESS = "SUBMIT_EMPLOYEE_SUCCESS";
export const EMPLOYEES_API_ERROR = "EMPLOYEES_API_ERROR";
export const LOAD_EMPLOYEES = "LOAD_EMPLOYEES";
export const LOAD_EMPLOYEES_SUCCESS = "LOAD_EMPLOYEES_SUCCESS";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
