export const SUBMIT_INVESTMENT = "SUBMIT_INVESTMENT";
export const SUBMIT_INVESTMENT_SUCCESS = "SUBMIT_INVESTMENT_SUCCESS";
export const INVESTMENTS_API_ERROR = "INVESTMENTS_API_ERROR";
export const LOAD_INVESTMENTS = "LOAD_INVESTMENTS";
export const LOAD_INVESTMENTS_SUCCESS = "LOAD_INVESTMENTS_SUCCESS";
export const UPDATE_INVESTMENT = "UPDATE_INVESTMENT";
export const UPDATE_INVESTMENT_SUCCESS = "UPDATE_INVESTMENT_SUCCESS";
