export const SUBMIT_SELLER = "SUBMIT_SELLER";
export const SUBMIT_SELLER_SUCCESS = "SUBMIT_SELLER_SUCCESS";
export const UPDATE_SELLER = "UPDATE_SELLER";
export const UPDATE_SELLER_SUCCESS = "UPDATE_SELLER_SUCCESS";
export const LOAD_SELLERS = "LOAD_SELLERS";
export const LOAD_SELLERS_SUCCESS = "LOAD_SELLERS_SUCCESS";
export const SELLER_API_ERROR = "SELLER_API_ERROR";
