export const LOAD_SALES = "LOAD_SALES";
export const LOAD_SALES_SUCCESS = "LOAD_SALES_SUCCESS";
export const LOAD_ACCOUNTS = "LOAD_ACCOUNTS";
export const LOAD_ACCOUNTS_SUCCESS = "LOAD_ACCOUNTS_SUCCESS";
export const REPORTS_API_ERROR = "REPORTS_API_ERROR";
