export const SUBMIT_INCOME = "SUBMIT_INCOME";
export const SUBMIT_INCOME_SUCCESS = "SUBMIT_INCOME_SUCCESS";
export const INCOMES_API_ERROR = "INCOMES_API_ERROR";
export const LOAD_INCOMES = "LOAD_INCOMES";
export const LOAD_INCOMES_SUCCESS = "LOAD_INCOMES_SUCCESS";
